server:
  port: 2333
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://192.168.198.128:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 192.168.198.128
    password: 123456