server:
  port: 2333
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://localhost:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456